In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import pandas_datareader as pdr
data = []
for i in range(1,41):
  with open("/content/drive/My Drive/Colab_Notebooks/簡媜/"+str(i)+".txt.txt") as f:
    lines = f.readlines()
    count = 0 
    while count < len(lines):
      if lines[count] =='\n':
        del lines[count]
      count +=1  
    print(lines)
    data+=lines
print(data)

['台大的醉月湖记载着一个故事，关于一名困情女子投水的传说。我想，深情即是一桩悲剧 必得以死来句读。而这种死也是最纯洁的。我是名弱者，欣赏了悲剧也扮演过悲剧，却在最后一幕潜逃，人是活着，热情已死。因此我写下水问。纪念那位女子并追悼自己。\n', '那年的杜鹃已化做次年的春泥，为何，为何你的湖水碧绿依然如今？\n', '那年的人事已散成凡间的风尘，为何，为何你的春闺依旧年年年轻？\n', '是不是柳烟太浓密，你寻不着春日的门扉？\n', '是不是栏杆太纵横，你潜不出涕泣的沼泽？\n', '是不是湖中无堤无桥，你泅不到芳香的草岸？\n', '传说太多，也太粗糙：说你只不过是曾经花城的孤单女子，因不慎而溺于爱的歧流断脉之中，说你的失足只是一种意外。说有人见你午夜低徊于水陆的边缘，羞怯的向陌生的行人诉说你破碎的心肠，说你千里迢迢要来赴那人的盟约，然而千里迢迢怎是你所能跋涉？日夜的次序又怎能容你轻易嵌入？你已不属于时间空间，你因而被镇于湖心水湄，再不敢向人间，向你钟爱的人间殷殷探询。你于是成了一只冷僵了的蝴蝶标本，在图鉴上注明因求偶不成而自戕，被传阅于唇齿残香的茶余饭后。\n', '要问你:\n', '天空这么温柔的包容着大地，为何你不送走今日且待明日？\n', '大地这么宽厚的载育着万物，为何你不掏穴别居另成家室？\n', '人间婚姻的手续这么简单，为何你独独择水为你最后的归宿？\n', '是不是你信念着，有一种无缘由而起的宇宙最初要持续到无缘由而去的宇宙最后的一种约誓，让你飘零过千万年的混沌，于此生此身为人，要在人间相寻相觅？你是离群的雁，甘愿于人间的尘网，折翅敛羽，要寻百年前流散于洪流乱烟中的另一只孤雁？你走过多少个春去秋来，多少丈人间红尘，你来到那人面前，虽然人间铸他以泥沤，你依旧认出那疲惫的面容正是你的魂梦所系，那沙哑的嗓音正是你所盼望的清脆。你从他的眼眸看出你最原始的身影，你知道，那是你们唯一的辨认。\n', '人间的鹊桥，虽不如天庭的绚丽，而你们愿意一砖一瓦的建筑。\n', '人间的气候，虽不如天庭的清朗，而你们羽翼同飞要共地坼天裂的风暴。\n', '人间的箪食瓢饮，虽不如天庭的琼浆玉液，而你们饭蔬食饮甘之如饴。\n', '生命的意义原本就模糊不清，在纷杂的爱之向度中，你们愿意凸显爱情为你们心中的殿堂。以千年的姻缘，作最坚固的奠基，以信任与尊敬，作不朽的钢架，深

In [ ]:
words= ""
for line in data:
  tmp = line.replace('\n','').replace('-','').replace(' ','')
  words+=tmp

In [ ]:
n = len(words)
w = len(set(words))
print(f"簡媜散文共有 {n} 中文字")
print(f"包含了 {w} 個獨一無二的字")

簡媜散文共有 54654 中文字
包含了 3111 個獨一無二的字


In [ ]:
import tensorflow as tf
num_words = len(set(words))
# initialize the tokenizer
tokenizer = tf.keras\
    .preprocessing\
    .text\
    .Tokenizer(
        num_words=num_words,
        char_level=True,
        filters=''
)

# 讓 tokenizer 讀過天龍八部全文，
# 將每個新出現的字加入字典並將中文字轉
# 成對應的數字索引
tokenizer.fit_on_texts(words)
text_as_int = tokenizer\
    .texts_to_sequences([words])[0]

# 隨機選取一個片段文本方便之後做說明
s_idx = 21004
e_idx = 21020
partial_indices = \
    text_as_int[s_idx:e_idx]
partial_texts = [
    tokenizer.index_word[idx] \
    for idx in partial_indices
]

# 渲染結果，可忽略
print("原本的中文字序列：")
print()
print(partial_texts)
print()
print("-" * 20)
print()
print("轉換後的索引序列：")
print()
print(partial_indices)

原本的中文字序列：

['践', '理', '想', '中', '的', '美', '，', '愈', '来', '愈', '不', '可', '得', '，', '触', '目']

--------------------

轉換後的索引序列：

[2243, 167, 60, 37, 2, 145, 1, 291, 15, 291, 6, 73, 34, 1, 1011, 356]


In [ ]:
print(dict(tokenizer.index_word))

{1: '，', 2: '的', 3: '。', 4: '一', 5: '我', 6: '不', 7: '是', 8: '你', 9: '人', 10: '在', 11: '了', 12: '有', 13: '地', 14: '、', 15: '来', 16: '上', 17: '她', 18: '那', 19: '着', 20: '这', 21: '时', 22: '之', 23: '也', 24: '？', 25: '到', 26: '们', 27: '自', 28: '为', 29: '而', 30: '个', 31: '生', 32: '天', 33: '然', 34: '得', 35: '如', 36: '以', 37: '中', 38: '心', 39: '里', 40: '下', 41: '出', 42: '无', 43: '过', 44: '大', 45: '小', 46: '只', 47: '去', 48: '他', 49: ',', 50: '”', 51: '“', 52: '水', 53: '子', 54: '看', 55: '声', 56: '间', 57: '要', 58: '能', 59: '么', 60: '想', 61: '与', 62: '会', 63: '情', 64: '后', 65: '：', 66: '身', 67: '好', 68: '像', 69: '说', 70: '回', 71: '！', 72: '多', 73: '可', 74: '成', 75: '起', 76: '就', 77: '对', 78: '年', 79: '又', 80: '道', 81: '头', 82: '面', 83: '当', 84: '从', 85: '于', 86: '.', 87: '山', 88: '；', 89: '已', 90: '风', 91: '花', 92: '还', 93: '都', 94: '…', 95: '己', 96: '走', 97: '手', 98: '知', 99: '它', 100: '意', 101: '「', 102: '」', 103: '空', 104: '事', 105: '最', 106: '日', 107: '前', 108: '把', 109: '路', 110: '开', 111: '世

In [ ]:
_type = type(text_as_int)
n = len(text_as_int)
print(f"text_as_int 是一個 {_type}\n")
print(f"小說的序列長度： {n}\n")
print("前 5 索引：", text_as_int[:5])

text_as_int 是一個 <class 'list'>

小說的序列長度： 54654

前 5 索引： [499, 44, 2, 1119, 234]


In [ ]:
# 方便說明，實際上我們會用更大的值來
# 讓模型從更長的序列預測下個中文字
SEQ_LENGTH = 10  # 數字序列長度
BATCH_SIZE = 128 # 幾筆成對輸入/輸出

# text_as_int 是一個 python list
# 我們利用 from_tensor_slices 將其
# 轉變成 TensorFlow 最愛的 Tensor <3
characters = tf\
    .data\
    .Dataset\
    .from_tensor_slices(
        text_as_int)

# 將被以數字序列表示的天龍八部文本
# 拆成多個長度為 SEQ_LENGTH (10) 的序列
# 並將最後長度不滿 SEQ_LENGTH 的序列捨去
sequences = characters\
    .batch(SEQ_LENGTH + 1, 
           drop_remainder=True)

# 天龍八部全文所包含的成對輸入/輸出的數量
steps_per_epoch = \
    len(text_as_int) // SEQ_LENGTH

# 這個函式專門負責把一個序列
# 拆成兩個序列，分別代表輸入與輸出
# （下段有 vis 解釋這在做什麼）
def build_seq_pairs(chunk):
    input_text = chunk[:-1]
    target_text = chunk[1:]
    return input_text, target_text

# 將每個從文本擷取出來的序列套用上面
# 定義的函式，拆成兩個數字序列
# 作為輸入／輸出序列
# 再將得到的所有數據隨機打亂順序
# 最後再一次拿出 BATCH_SIZE（128）筆數據
# 作為模型一次訓練步驟的所使用的資料
ds = sequences\
    .map(build_seq_pairs)\
    .shuffle(steps_per_epoch)\
    .batch(BATCH_SIZE, 
           drop_remainder=True)

In [ ]:
ds

<BatchDataset shapes: ((128, 10), (128, 10)), types: (tf.int32, tf.int32)>

In [ ]:
for b_inp, b_tar in ds.take(1):
    print("起始句子的 batch：")
    print(b_inp, "\n")
    print("目標句子的 batch：")
    print(b_tar, "\n")
    print("-" * 20, "\n")
    
    print("第一個起始句子的索引序列：")
    first_i = b_inp.numpy()[0]
    print(first_i, "\n")
    print("第一個目標句子的索引序列：")
    first_t = b_tar.numpy()[0]
    print(first_t, "\n")
    print("-" * 20, "\n")
    
    d = tokenizer.index_word
    print("第一個起始句子的文本序列：")
    print([d[i] for i in first_i])
    print()
    print("第一個目標句子的文本序列：")
    print([d[i] for i in first_t])

起始句子的 batch：
tf.Tensor(
[[616  11   2 ...   4 604 229]
 [459 800  93 ...   2   6   7]
 [  1   7  99 ...  12 674 144]
 ...
 [101 816 303 ... 199 137 295]
 [473 128   2 ...  10  87 292]
 [198 457  11 ... 848  53 163]], shape=(128, 10), dtype=int32) 

目標句子的 batch：
tf.Tensor(
[[  11    2    1 ...  604  229 1105]
 [ 800   93  279 ...    6    7  459]
 [   7   99   26 ...  674  144    2]
 ...
 [ 816  303 1241 ...  137  295  102]
 [ 128    2  786 ...   87  292  753]
 [ 457   11    1 ...   53  163  119]], shape=(128, 10), dtype=int32) 

-------------------- 

第一個起始句子的索引序列：
[616  11   2   1  79 141 699   4 604 229] 

第一個目標句子的索引序列：
[  11    2    1   79  141  699    4  604  229 1105] 

-------------------- 

第一個起始句子的文本序列：
['废', '了', '的', '，', '又', '何', '止', '一', '块', '门']

第一個目標句子的文本序列：
['了', '的', '，', '又', '何', '止', '一', '块', '门', '牌']


In [ ]:
# 超參數
EMBEDDING_DIM = 512
RNN_UNITS = 1024

# 使用 keras 建立一個非常簡單的 LSTM 模型
model = tf.keras.Sequential()

# 詞嵌入層
# 將每個索引數字對應到一個高維空間的向量
model.add(
    tf.keras.layers.Embedding(
        input_dim=num_words, 
        output_dim=EMBEDDING_DIM,
        batch_input_shape=[
            BATCH_SIZE, None]
))

# LSTM 層
# 負責將序列數據依序讀入並做處理
model.add(
    tf.keras.layers.LSTM(
    units=RNN_UNITS, 
    return_sequences=True, 
    stateful=True, 
    recurrent_initializer='glorot_uniform'
))

# 全連接層
# 負責 model 每個中文字出現的可能性
model.add(
    tf.keras.layers.Dense(
        num_words))

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (128, None, 512)          1592832   
_________________________________________________________________
lstm_3 (LSTM)                (128, None, 1024)         6295552   
_________________________________________________________________
dense_3 (Dense)              (128, None, 3111)         3188775   
Total params: 11,077,159
Trainable params: 11,077,159
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 超參數，決定模型一次要更新的步伐有多大
LEARNING_RATE = 0.001

# 定義模型預測結果跟正確解答之間的差異
# 因為全連接層沒使用 activation func
# from_logits= True 
def loss(y_true, y_pred):
    return tf.keras.losses\
    .sparse_categorical_crossentropy(
        y_true, y_pred, from_logits=True)

# 編譯模型，使用 Adam Optimizer 來最小化
# 剛剛定義的損失函數
model.compile(
    optimizer=tf.keras\
        .optimizers.Adam(
        learning_rate=LEARNING_RATE), 
    loss=loss
)

In [ ]:
EPOCHS =400
callbacks = [
    tf.keras.callbacks\
        .TensorBoard("logs"),
    # 你可以加入其他 callbacks 如
    # ModelCheckpoint,
    # EarlyStopping
]

history = model.fit(
    ds,
    epochs=EPOCHS, 
    callbacks=callbacks
)

Epoch 1/400
38/38 [==============================] - 5s 84ms/step - loss: 6.8505
Epoch 2/400
38/38 [==============================] - 3s 69ms/step - loss: 6.4868
Epoch 3/400
38/38 [==============================] - 3s 70ms/step - loss: 6.3615
Epoch 4/400
38/38 [==============================] - 3s 70ms/step - loss: 6.1916
Epoch 5/400
38/38 [==============================] - 3s 70ms/step - loss: 6.0064
Epoch 6/400
38/38 [==============================] - 3s 70ms/step - loss: 5.8109
Epoch 7/400
38/38 [==============================] - 3s 69ms/step - loss: 5.6092
Epoch 8/400
38/38 [==============================] - 3s 69ms/step - loss: 5.4095
Epoch 9/400
38/38 [==============================] - 3s 68ms/step - loss: 5.2026
Epoch 10/400
38/38 [==============================] - 3s 69ms/step - loss: 4.9952
Epoch 11/400
38/38 [==============================] - 3s 69ms/step - loss: 4.7792
Epoch 12/400
38/38 [==============================] - 3s 71ms/step - loss: 4.5600
Epoch 13/400
38/38 [=====

In [ ]:
model.save('/content/drive/My Drive/Colab_Notebooks/first.h5')

In [ ]:
#跟訓練時一樣的超參數，
# 只差在 BATCH_SIZE 為 1
EMBEDDING_DIM = 512
RNN_UNITS = 1024
BATCH_SIZE = 1

# 專門用來做生成的模型
infer_model = tf.keras.Sequential()

# 詞嵌入層
infer_model.add(
    tf.keras.layers.Embedding(
        input_dim=num_words, 
        output_dim=EMBEDDING_DIM,
        batch_input_shape=[
            BATCH_SIZE, None]
))

# LSTM 層
infer_model.add(
    tf.keras.layers.LSTM(
    units=RNN_UNITS, 
    return_sequences=True, 
    stateful=True
))

# 全連接層
infer_model.add(
    tf.keras.layers.Dense(
        num_words))

# 讀入之前訓練時儲存下來的權重
infer_model.load_weights('/content/drive/My Drive/Colab_Notebooks/first.h5')
infer_model.build(
    tf.TensorShape([1, None]))

In [ ]:
# 代表「台」的索引
seed_indices = [421] 
temperature =0.1
# 增加 batch 維度丟入模型取得預測結果後
# 再度降維，拿掉 batch 維度
input = tf.expand_dims(
    seed_indices, axis=0)
predictions = infer_model(input)
predictions = tf.squeeze(
    predictions, 0)
print(predictions)
# 利用生成溫度影響抽樣結果
predictions /= temperature
print(predictions)
# 從 4330 個分類值中做抽樣
# 取得這個時間點模型生成的中文字
sampled_indices = tf.random\
    .categorical(
        predictions, num_samples=1)

tf.Tensor([[-3.2781572  4.616811   6.8533335 ... -2.6991563 -2.1338093 -5.3670444]], shape=(1, 3111), dtype=float32)
tf.Tensor([[-32.78157   46.168106  68.53333  ... -26.991562 -21.338093 -53.670444]], shape=(1, 3111), dtype=float32)


In [ ]:
import numpy as np 
output = tokenizer.index_word[np.array(sampled_indices)[0][0]]
print(output, end='')

场

In [ ]:
#build word to int
word_to_num = {}
for key, value in  tokenizer.index_word.items():
  word_to_num[value] = key

print(word_to_num)

{'，': 1, '的': 2, '。': 3, '一': 4, '我': 5, '不': 6, '是': 7, '你': 8, '人': 9, '在': 10, '了': 11, '有': 12, '地': 13, '、': 14, '来': 15, '上': 16, '她': 17, '那': 18, '着': 19, '这': 20, '时': 21, '之': 22, '也': 23, '？': 24, '到': 25, '们': 26, '自': 27, '为': 28, '而': 29, '个': 30, '生': 31, '天': 32, '然': 33, '得': 34, '如': 35, '以': 36, '中': 37, '心': 38, '里': 39, '下': 40, '出': 41, '无': 42, '过': 43, '大': 44, '小': 45, '只': 46, '去': 47, '他': 48, ',': 49, '”': 50, '“': 51, '水': 52, '子': 53, '看': 54, '声': 55, '间': 56, '要': 57, '能': 58, '么': 59, '想': 60, '与': 61, '会': 62, '情': 63, '后': 64, '：': 65, '身': 66, '好': 67, '像': 68, '说': 69, '回': 70, '！': 71, '多': 72, '可': 73, '成': 74, '起': 75, '就': 76, '对': 77, '年': 78, '又': 79, '道': 80, '头': 81, '面': 82, '当': 83, '从': 84, '于': 85, '.': 86, '山': 87, '；': 88, '已': 89, '风': 90, '花': 91, '还': 92, '都': 93, '…': 94, '己': 95, '走': 96, '手': 97, '知': 98, '它': 99, '意': 100, '「': 101, '」': 102, '空': 103, '事': 104, '最': 105, '日': 106, '前': 107, '把': 108, '路': 109, '开': 110, '世': 11

In [ ]:
# start = input('測試開始')
start = "他拿起刀說"
s = int(word_to_num[start[0]])
# generate_length = int(input('欲輸出文章長度'))
generate_length = 500
count = 0 
print("起始: ",start)
temperature =0.23

while count < generate_length:
  seed_indices = [s] 
  
  # 增加 batch 維度丟入模型取得預測結果後
  # 再度降維，拿掉 batch 維度
  input = tf.expand_dims(
      seed_indices, axis=0)

  predictions = infer_model(input)
  predictions = tf.squeeze(
      predictions, 0)

  # 利用生成溫度影響抽樣結果
  predictions /= temperature

  # 從 4330 個分類值中做抽樣
  # 取得這個時間點模型生成的中文字
  sampled_indices = tf.random\
      .categorical(
          predictions, num_samples=1)
  s = np.array(sampled_indices)[0][0]
  output = tokenizer.index_word[s]
  print(output, end = '')
  count +=1
  if count%50==0:
    print()


起始:  他拿起刀說
已组装铁架、挂勾，一面时时叩问生之哲理讲到底的女人。杯、盘托出，人的有情必须放着风筝。我桌上的咖啡壶
那出来再煮它一壶酒呢！还在，经过文字的南柯一条是山路，铺了柏油，迂回前进。我也从低头疾。伊会在发湄簪
两朵红花，没看见坐在路边的我的花园！”你视为护符藏入袍袖。却被虎风卷出，你欲凌空追回蝴蝶，甫扬臂，敌
者的宝剑刺穿心胸。孤寂之夜。你试图站起，惊觉身体已化为躺卧的岩峰，那把剜心剑吮吸你的鲜血，竟长成了参
天红桧，你才知道，战争已是千年旧事了。蓊郁的树林，莽草及花丛，在岁月中，一一爬上你的肤体，招来夜枭及
风的情歌，仿佛乐园。你仰望繁星，那熠熠的星子，莫非伊人亲手点的寻人灯？啊！败神不死，乃最残酷的魔咒；
生既不能生，死不得死，神非神，人非人。泪，自你的眼眶溢出，如一缕银丝，在残月照耀下，发出悲凄的光。忽
然，从黑暗的岩隙飞出一只青蝴蝶，停在你的泪泉上拍翅，一小口又一小口，吮食银泪。破晓时分，最后一滴泪也
饮了。“让蝴蝶飞在前头，引着胜利的你回到我的花园！”你视为护符藏入袍袖。却被虎风卷出，你欲凌空追回蝴
蝶，甫扬臂，敌者的宝剑刺穿心胸。孤寂之夜。你试图站起，惊觉身体已化为躺卧的岩峰，那把剜心剑吮吸你的鲜


In [ ]:
infer_model.save('/content/drive/My Drive/Colab_Notebooks/third.h5')